"""empty message

Revision ID: 32447ce3b771
Revises: 04d4f062ee8d
Create Date: 2026-02-20 20:26:20.325257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32447ce3b771'
down_revision = '04d4f062ee8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
